import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = readFileSync(join(root, "src/styles.css"), "utf8");
const { code: css } = await esbuild.transform(source, {
  loader: "css",
  minify: true
});

writeFileSync(
  join(root, "src/styles.generated.ts"),
  `/* Auto-generated by scripts/embed-css.mjs — do not edit manually. */\nexport const CORNBAR_CSS = ${JSON.stringify(css)};\n`
);

console.log("Embedded minified cornbar CSS into src/styles.generated.ts");
