import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const css = readFileSync(join(root, "src/styles.css"), "utf8");

writeFileSync(
  join(root, "src/styles.generated.ts"),
  `/* Auto-generated by scripts/embed-css.mjs — do not edit manually. */\nexport const CORNBAR_CSS = ${JSON.stringify(css)};\n`
);

console.log("Embedded cornbar CSS into src/styles.generated.ts");
